# Generated by Django 5.1.2 on 2024-11-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_email_address_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_address',
        ),
    ]
