# Generated by Django 5.1.2 on 2024-11-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sdt',
            field=models.CharField(max_length=55, null=True, unique=True, verbose_name='Sdt'),
        ),
    ]
