# Generated by Django 5.1.2 on 2024-11-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
