# Generated by Django 5.1.2 on 2024-11-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_post_remove_comment_created_date_comment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='body',
        ),
    ]
