# Generated by Django 5.1.2 on 2024-11-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_article_rename_author_comment_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
