# Generated by Django 5.1.2 on 2024-11-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_rename_date_article_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
    ]
