# Generated by Django 5.1.2 on 2024-12-01 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_post_alter_comment_post'),
        ('home', '0014_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.article'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
